version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: haopham1412/api-wapper-clean-architecture:latest
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=Book
      - DB_USER=postgres
      - DB_PASSWORD=12345
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: Book
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: